export async function seed(knex) {
  await knex('baskets').del()

  await knex('baskets').insert([
    {
      id: 1,
      user_id: 'auth|123',
      description: 'Fresh vegetables and fruits for a healthy diet.',
      categories: 'Vegetables,Fruit',
      dietary_content: 'Vegan,GlutenFree',
      location: 'NorthShore',
      status: 'active',
      created_at: 1698557400000,
      updated_at: 1698557700000,
    },
    {
      id: 2,
      user_id: 'auth|456',
      description: 'Mixed fruits basket for a nutritious snack.',
      categories: 'Fruit,Snacks',
      dietary_content: 'Vegetarian,GlutenFree',
      location: 'SouthAuckland',
      status: 'active',
      created_at: 1698559200000,
      updated_at: 1698559500000,
    },
    {
      id: 3,
      user_id: 'auth|789',
      description: 'Fresh seafood and eggs for a protein-packed meal.',
      categories: 'Seafood,Eggs',
      dietary_content: 'Halal',
      location: 'EastAuckland',
      status: 'active',
      created_at: 1698561600000,
      updated_at: 1698561900000,
    },
    {
      id: 4,
      user_id: 'auth|101',
      description: 'Variety of meats for a protein-rich diet.',
      categories: 'Meat',
      dietary_content: 'GlutenFree,Halal',
      location: 'WestAuckland',
      status: 'active',
      created_at: 1698564000000,
      updated_at: 1698564300000,
    },
    {
      id: 5,
      user_id: 'auth|202',
      description: 'Eggs and dairy items for a balanced diet.',
      categories: 'Eggs,Dairy',
      dietary_content: 'Vegetarian,GlutenFree',
      location: 'NorthShore',
      status: 'active',
      created_at: 1698566400000,
      updated_at: 1698566700000,
    },
    {
      id: 6,
      user_id: 'auth|123',
      description: 'Assorted snacks including chips and confectionery.',
      categories: 'Snacks',
      dietary_content: 'Vegetarian',
      location: 'SouthAuckland',
      status: 'active',
      created_at: 1698568800000,
      updated_at: 1698569100000,
    },
    {
      id: 7,
      user_id: 'auth|456',
      description: 'Canned foods for emergency supplies.',
      categories: 'Canned',
      dietary_content: 'GlutenFree,Halal',
      location: 'EastAuckland',
      status: 'active',
      created_at: 1698571200000,
      updated_at: 1698571500000,
    },
    {
      id: 8,
      user_id: 'auth|789',
      description: 'Baking ingredients for your next cake.',
      categories: 'Baking',
      dietary_content: 'Vegetarian',
      location: 'WestAuckland',
      status: 'active',
      created_at: 1698573600000,
      updated_at: 1698573900000,
    },
    {
      id: 9,
      user_id: 'auth|101',
      description: 'Healthy carbs like rice and pasta for meals.',
      categories: 'Carbs',
      dietary_content: 'Vegan,GlutenFree',
      location: 'NorthShore',
      status: 'active',
      created_at: 1698576000000,
      updated_at: 1698576300000,
    },
    {
      id: 10,
      user_id: 'auth|202',
      description: 'Assorted dairy and beverages for a light meal.',
      categories: 'Dairy,Beverages',
      dietary_content: 'GlutenFree,Halal',
      location: 'SouthAuckland',
      status: 'active',
      created_at: 1698578400000,
      updated_at: 1698578700000,
    },
  ])
}
